services:
  db:
    # The inquire database - central to all services
    image: 'postgres:16'
    command: -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key
    volumes:
      - 'postgres_db:/data'
      - './ca/server.crt:/var/lib/postgresql/server.crt'
      - './ca/server.key:/var/lib/postgresql/server.key'
    environment:
      PGDATA: '/data/pgdata'
      POSTGRES_PASSWORD: "db_password" # only on first run
      POSTGRES_USER: "db_user"
      POSTGRES_DB: "db"
    ports:
      - '5432:5432'
    restart: unless-stopped

volumes:
  postgres_db:
